# Generated by Django 5.0.4 on 2024-05-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='testdescription',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
