# Generated by Django 5.0.4 on 2024-05-12 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_test_testdescription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
